"""
Running this build script will generate a new exe file in the /dist directory.
"""

import os

c_string = [
    'PyInstaller',
    'main.py',
    '--onefile',
    '--clean',
    '--key horrible-aes-key',
    '--exclude-module scipy',
    '--exclude-module setuptools',
    '--exclude-module hook',
    '--exclude-module site',
    '--exclude-module hooks',
    '--exclude-module PyQt4',
    '--exclude-module PyQt5',
    '--exclude-module pydoc',
    '--exclude-module pythoncom',
    '--exclude-module pytz',
    '--exclude-module pywintypes',
    '--exclude-module sqlite3',
    '--exclude-module pyz',
    '--exclude-module pandas',
    '--exclude-module sklearn',
    '--exclude-module scapy',
    '--exclude-module scrapy',
    '--exclude-module sympy',
    '--exclude-module kivy',
    '--exclude-module pyramid',
    '--exclude-module opencv',
    '--exclude-module tensorflow',
    '--exclude-module pipenv',
    '--exclude-module pattern',
    '--exclude-module mechanize',
    '--exclude-module beautifulsoup4',
    '--exclude-module requests',
    '--exclude-module wxPython',
    '--exclude-module pygi',
    '--exclude-module pillow',
    '--exclude-module pygame',
    '--exclude-module pyglet',
    '--exclude-module flask',
    '--exclude-module django',
    '--exclude-module pylint',
    '--exclude-module pytube',
    '--exclude-module odfpy',
    '--exclude-module mccabe',
    '--exclude-module pilkit',
    '--exclude-module wrapt',
    '--exclude-module astroid',
    '--exclude-module isort',

    '--exclude-module plotly',
    '--exclude-module memory-profiler',
    '--exclude-module zipp',
    '--exclude-module altgraph',
    '--exclude-module cx-Freeze',
    '--exclude-module cx-Logging',
    '--exclude-module Nuitka',
    '--exclude-module pefile',
    '--exclude-module Pillow',
    '--exclude-module psutil',
    '--exclude-module Pillow',
    '--exclude-module py2exe',

    # '--exclude-module tinyaes',
    # '--exclude-module six',
    # '--exclude-module numpy',
    # '--exclude-module matplotlib',
    # '--icon icon.ico',
    '--name GenerateFigureFromFile'
]

fstr = " ".join(c_string)
os.system(fstr)
